name: Android CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # This line enables manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Generate debug keystore
      run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Rename APK
      run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/adhanalarm.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: adhanalarm
        path: app/build/outputs/apk/release/adhanalarm.apk

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: app/build/outputs/apk/release/adhanalarm.apk
